--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/RKAbdul/OreSpawners
build-by-default: true
branches:
- master
projects:
  OreSpawners:
    path: ""
    libs:
    - src: DenielWorld/EzTiles/libEzTiles
      version: ^0.1.0
...
