name: OreSpawners
version: 0.3.1
main: RKAbdul\OreSpawners\Main
authors: [RKAbdul, AGTHARN]
api: 3.0.0

commands:
 orespawner:
  description: Give ore spawner.
  usage: "/orespawner [ore] [amount] [player]"
  aliases: ["os"]
  permission: "orespawner.give"
